"""Whole-session cam4 pose inference on HMS O2: build a self-contained BUNDLE on the share, print the commands to
run it, and collect the results back into the session-analysis format.

    python -m wfield_local.o2_inference bundle  --name r3_ps93 --user ab123 PS93:20260814 PS93:20260821 ...
    python -m wfield_local.o2_inference collect --name r3_ps93               # after the outputs are copied back

PORTED FROM stroke_orofacial_pipeline `dlc_inference_o2/` (batch.py, o2_job.py, runner.py, transfer.py; Priya
2026-10-02: "it will need refining and editing but was a way to run dlc on the server. lets port and modify").
KEPT: Python GENERATES the ssh / rsync / sbatch commands and you paste them -- nothing here logs in to O2 or
handles a password (O2 needs DUO; their 2026-04-18 decision). The two-hop data path (research.files is visible
only on the TRANSFER node: stage to /n/scratch there, compute on GPU nodes, copy back there). One GPU per job.
CHANGED:
  * The bundle lives ON THE SHARE (`<DeepLabCut/Widefield>/o2/<name>/`), so the transfer node pulls it straight
    from /n/files -- nothing has to be copied from this desktop to O2.
  * Prediction = `o2_pose_runner.py` (copied into the bundle): our model + the `dlc_prior` heatmap prior, i.e.
    the same numbers as local inference (theirs: `deeplabcut.analyze_videos`, which would skip the prior;
    TensorFlow, shuffle 5, allow_growth, snapshot renaming -- all gone with DLC 3 / PyTorch).
  * A job ARRAY, one task per video (theirs: one job looping over every video for 9.5 h), each task resumable in
    chunks, with --requeue: a preempted or time-limited task resumes where it stopped.
  * Videos: our cam4 tree (`Behavior_Cameras/Widefield/<date>/<animal>/cam4_*.avi`), not their 2pRAM `video2_*`.
  * `collect` checks every video's frame count against the predictions and turns the whole-video CSV into the
    per-trial windows the session analyses read (`session_poses/<animal>_<date>_full/`).
O2 facts to re-check before a big run (they change): partition names / time limits (`sinfo`), the conda module
name, and which CUDA the GPU nodes' driver supports (pick the torch wheel to match).
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

import numpy as np
import pandas as pd

from wfield_local import config

SHARE_PREFIX_O2 = "/n/files/Neurobio/MICROSCOPE/Priya"   # research.files path of the `microscope` root on O2


def params() -> dict:
    return dict(config.defaults().get("o2_inference") or {})


def true_case(path: Path) -> Path:
    """``path`` with every existing component spelled as it is ON DISK.

    Windows / SMB resolve names case-insensitively, so `configs/paths.yaml` has carried
    ``Behavior_Cameras/Widefield`` for months while the folders are ``Behavior_cameras/widefield`` (found
    2026-10-05). O2 is Linux: a path that works here can fail there. Components that do not exist (yet) are
    kept as given."""
    path = Path(path)
    out = Path(path.anchor)
    for part in path.parts[len(path.anchor and path.parts[:1]):]:
        try:
            match = next((c.name for c in out.iterdir() if c.name.lower() == part.lower()), part)
        except OSError:
            match = part
        out = out / match
    return out


def o2_path(local, rv) -> str:
    """A path under the `microscope` share root -> the same path as O2's transfer node sees it, in the
    on-disk case (`true_case`)."""
    root = true_case(Path(rv.root("microscope"))).as_posix().rstrip("/")
    p = true_case(Path(local)).as_posix()
    if not p.lower().startswith(root.lower()):
        raise ValueError(f"{p} is not under the share root {root}; O2 cannot see it")
    return SHARE_PREFIX_O2 + p[len(root):]


def scratch(user: str, p: dict | None = None) -> str:
    p = p or params()
    return p["scratch_root"].format(u0=user[0], user=user)


def bundle_dir(rv, name: str) -> Path:
    from wfield_local import dlc_project
    return dlc_project.project_dir(rv).parent / "o2" / name


def videos_for(rv, animal: str, date: str) -> list[Path]:
    return sorted((Path(rv.root("behavior_cameras")) / date / animal).glob("cam4_*.avi"))


def sbatch_text(p: dict, user: str, name: str, n_tasks: int) -> str:
    s = scratch(user, p)
    b = f"{s}/o2/{name}"
    return f"""#!/bin/bash -l
#SBATCH -J pose_{name}
#SBATCH -p {p['partition']}
#SBATCH --gres={p['gres']}
#SBATCH -c {p['cpus_per_task']}
#SBATCH --mem={p['mem']}
#SBATCH -t {p['time']}
#SBATCH --array=1-{n_tasks}%{p['max_concurrent']}
#SBATCH --requeue
#SBATCH -o {b}/logs/%A_%a.out
#SBATCH -e {b}/logs/%A_%a.err
{f"#SBATCH --exclude={p['exclude_nodes']}" if p.get('exclude_nodes') else ''}
# Generated by wfield_local.o2_inference -- regenerate rather than edit. One array task = one video; a re-run or
# requeue resumes from the last finished chunk. Login shell (-l) + `conda activate`, as the working 2025-11 O2
# script; no `set -u` (conda's activate scripts reference unset variables).
set -eo pipefail
module load {p['conda_module']}
conda activate {p['conda_env']}
LINE=$(awk -v n="$SLURM_ARRAY_TASK_ID" -F'\\t' 'NR==n+1' {b}/tasks.tsv)
ANIMAL=$(echo "$LINE" | cut -f2); DATE=$(echo "$LINE" | cut -f3); VIDEO=$(echo "$LINE" | cut -f4)
echo "task $SLURM_ARRAY_TASK_ID: $ANIMAL $DATE $VIDEO on $(hostname)"; nvidia-smi || true
python {b}/o2_pose_runner.py --bundle {b} --video {s}/o2_videos/$DATE/$ANIMAL/$VIDEO \\
    --out {b}/out/${{ANIMAL}}_${{DATE}} --batch {p['batch']} --chunk {p['chunk']}
"""


def commands_text(p: dict, user: str, name: str, share_b: str, tasks: pd.DataFrame) -> str:
    s = scratch(user, p)
    b = f"{s}/o2/{name}"
    stage = "\n".join(f"rsync -ah --partial --info=progress2 {r.video_o2}  {s}/o2_videos/{r.date}/{r.animal}/"
                      for r in tasks.itertuples())
    mk = " ".join(sorted({f"{s}/o2_videos/{r.date}/{r.animal}" for r in tasks.itertuples()}))
    return f"""# O2 run `{name}` -- {len(tasks)} video(s). Paste these yourself; nothing here logs in for you.
# Generated by `python -m wfield_local.o2_inference bundle`. Bundle on the share: {share_b}

## 0. Check the EXISTING env (Priya's O2 login already has `{p['conda_env']}` -- the env the 2025-11 stroke_orofacial
##    O2 runs used, PyTorch DLC 3 models). Our runner needs DLC 3.x (tested with {p['deeplabcut_version']}).
ssh {user}@o2.hms.harvard.edu
srun -p {p['partition']} --gres={p['gres']} -t 0:20:00 --mem=8G --pty bash
module load {p['conda_module']}
conda activate {p['conda_env']}
python -c "import torch, deeplabcut, cv2; print('torch', torch.__version__, 'cuda', torch.cuda.is_available(), 'dlc', deeplabcut.__version__, 'cv2', cv2.__version__)"
#   needs: cuda True and dlc 3.x. Step 2 (--bench) is the real check -- it builds the model and runs the prior.
#   FALLBACK only if the env is DLC 2.x / broken (do NOT modify the existing env -- other analyses use it):
#     conda create -y -n dlc3 python=3.10 && conda activate dlc3 && pip install "deeplabcut=={p['deeplabcut_version']}"
#     then set o2_inference.conda_env: dlc3 in configs/defaults.yaml and regenerate the bundle

## 1. Transfer node: bundle + videos -> scratch (research.files is visible only here)
ssh {user}@{p['transfer_host']}
mkdir -p {b} {mk}
rsync -ah --partial {share_b}/  {b}/
{stage}

## 2. FIRST RUN: smoke test + batch-size benchmark on a GPU node (proves the env runs OUR runner + prior)
ssh {user}@o2.hms.harvard.edu
srun -p {p['partition']} --gres={p['gres']} -t 0:30:00 --mem={p['mem']} --pty bash
module load {p['conda_module']}; conda activate {p['conda_env']}
python {b}/o2_pose_runner.py --bundle {b} --video {s}/o2_videos/{tasks.date.iloc[0]}/{tasks.animal.iloc[0]}/{tasks.video.iloc[0]} --bench 2000
#   -> if another batch size is clearly faster: set o2_inference.batch in configs/defaults.yaml, then
#      `python -m wfield_local.o2_inference bundle --refresh --name {name} --user {user} <same sessions>`
#      and re-run the bundle rsync in step 1 (only the text files change)

## 3. Login node: submit the array
ssh {user}@o2.hms.harvard.edu
mkdir -p {b}/logs && sbatch {b}/run_pose.sbatch

## 4. Monitor
squeue -u {user}
tail -f {b}/logs/*_1.out
ls {b}/out/*/*_done.json | wc -l          # finished videos (of {len(tasks)})

## 5. Transfer node: results -> the share (into the bundle folder)
ssh {user}@{p['transfer_host']}
rsync -ah --partial --exclude '*_chunks' {b}/out/  {share_b}/out/

## 6. This desktop: check + convert to the session-analysis format
python -m wfield_local.o2_inference collect --name {name}

## 7. Clean scratch when collected (scratch is purged after 45 days anyway)
rm -r {s}/o2_videos  {b}/out/*/*_chunks
"""


def cmd_bundle(rv, name: str, user: str, sessions: list[tuple[str, str]], refresh: bool = False) -> Path:
    from wfield_local import dlc_prior, dlc_train
    from wfield_local.dlc_iti_frames import current_snapshot
    p = params()
    d = bundle_dir(rv, name)
    if (d / "bundle.json").exists():
        if not refresh:
            raise SystemExit(f"{d} exists -- pick a new --name (a bundle is a record of what ran), or --refresh to "
                             f"rewrite only its generated text (sbatch, COMMANDS.md, runner)")
        # --refresh: regenerate the TEXT only -- the model, prior and task list stay exactly as bundled
        tasks = pd.read_csv(d / "tasks.tsv", sep="\t", dtype=str).drop(columns="task")
        # Same videos, re-SPELT in the on-disk case (`true_case`; bundles made before 2026-10-05 carry
        # paths.yaml's Behavior_Cameras/Widefield, which a case-sensitive O2 path lookup would not find).
        local = {(a, dt): {v.name: v for v in videos_for(rv, a, dt)} for a, dt in zip(tasks.animal, tasks.date)}
        tasks["video_o2"] = [o2_path(local[(a, dt)][v], rv) if v in local[(a, dt)] else o2
                             for a, dt, v, o2 in zip(tasks.animal, tasks.date, tasks.video, tasks.video_o2)]
        tasks.insert(0, "task", np.arange(1, len(tasks) + 1))
        tasks.to_csv(d / "tasks.tsv", sep="\t", index=False)
        tasks = tasks.drop(columns="task")
        shutil.copy2(Path(__file__).with_name("o2_pose_runner.py"), d / "o2_pose_runner.py")
        (d / "run_pose.sbatch").write_text(sbatch_text(p, user, name, len(tasks)), encoding="utf-8", newline="\n")
        (d / "COMMANDS.md").write_text(commands_text(p, user, name, o2_path(d, rv), tasks), encoding="utf-8",
                                       newline="\n")
        print(f"refreshed text in {d}")
        return d
    td, snap = current_snapshot(dlc_train.train_project(rv), None)
    box = dlc_prior.active(rv, cam="cam4") or {}
    rows = []
    for animal, date in sessions:
        vids = videos_for(rv, animal, date)
        if not vids:
            raise SystemExit(f"no cam4 video for {animal} {date} under {rv.root('behavior_cameras')}")
        rows += [{"animal": animal, "date": date, "video": v.name, "video_o2": o2_path(v, rv)} for v in vids]
    tasks = pd.DataFrame(rows)
    (d / "model").mkdir(parents=True)
    shutil.copy2(td / "pytorch_config.yaml", d / "model" / "pytorch_config.yaml")
    shutil.copy2(snap, d / "model" / snap.name)
    shutil.copy2(Path(__file__).with_name("o2_pose_runner.py"), d / "o2_pose_runner.py")
    scorer = f"DLC_{td.parent.parent.name}_{snap.stem}"          # e.g. DLC_iteration-2_snapshot-best-160
    (d / "bundle.json").write_text(json.dumps({
        "parts": list(dlc_train.parts()), "scorer": scorer, "pytorch_config": "model/pytorch_config.yaml",
        "snapshot": f"model/{snap.name}", "prior": {k: [float(v) for v in b] for k, b in box.items()},
        "source_train_dir": str(td), "created_for": user}, indent=1), encoding="utf-8")
    tasks.insert(0, "task", np.arange(1, len(tasks) + 1))
    tasks.to_csv(d / "tasks.tsv", sep="\t", index=False)
    (d / "run_pose.sbatch").write_text(sbatch_text(p, user, name, len(tasks)), encoding="utf-8", newline="\n")
    (d / "COMMANDS.md").write_text(commands_text(p, user, name, o2_path(d, rv), tasks), encoding="utf-8",
                                   newline="\n")
    print(f"bundle -> {d}  ({len(tasks)} videos; model {td.parent.parent.name}/{snap.name}; prior on "
          f"{', '.join(box) or 'nothing'})\nnext: follow {d / 'COMMANDS.md'}")
    return d


def full_to_windows(pose: np.ndarray, parts: list[str], scorer: str, animal: str, date: str, out: Path, rv,
                    pre_s: float = 0.5, post_s: float = 3.0, model: str = "DLC") -> int:
    """Whole-video predictions ``pose`` (n_frames, n_parts, 3) -> `session_poses`-format windows for EVERY trial
    (position strobe - pre_s .. trial stop + post_s): windows_index.csv (trial_k, trial_id, position, src_frame,
    t_ms, strobe_ms, stop_ms, stop_source) + windows_<model>.csv with the matching rows; the analyses then run
    unchanged. Takes the runner's .npz ARRAY, not its CSV: exact, and no 2-million-row parse (and a CSV whose
    first data row is empty would be misread by pandas' 3-row-header reader as an index-name row -- found
    2026-10-02 while testing this with a NaN-padded file)."""
    from wfield_local import dlc_frames as DF
    from wfield_local import trial_windows as TW
    tpl = dict(np.load(Path(rv.root("alignment_templates")) / "cam4" / animal / f"{date}.npz", allow_pickle=True))
    b = TW.trial_bounds(animal, date, rv)
    b = b[np.isfinite(b.cue_s) & np.isfinite(b.stop_s)].sort_values("cue_s").reset_index(drop=True)
    n_full = len(pose)
    idx, rows = [], []
    for k, r in enumerate(b.itertuples()):
        t0 = min(r.strobe_s, r.cue_s - pre_s) if np.isfinite(r.strobe_s) else r.cue_s - pre_s
        f0, f1 = DF.frame_of(tpl, t0 - pre_s, 0.0), DF.frame_of(tpl, r.stop_s + post_s, 0.0)
        fc = DF.frame_of(tpl, r.cue_s, 0.0)
        f0, f1 = max(0, f0), min(n_full, f1)
        for f in range(f0, f1):
            idx.append((k, int(r.trial_id), r.pos_name, f, (f - fc) * 4.0, (r.strobe_s - r.cue_s) * 1000.0,
                        (r.stop_s - r.cue_s) * 1000.0, r.stop_source))
        rows.append(np.arange(f0, f1))
    out.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(idx, columns=["trial_k", "trial_id", "position", "src_frame", "t_ms", "strobe_ms", "stop_ms",
                               "stop_source"]).to_csv(out / "windows_index.csv", index=False)
    sel = pose[np.concatenate(rows)]
    cols = pd.MultiIndex.from_product([[scorer], list(parts), ["x", "y", "likelihood"]],
                                      names=["scorer", "bodyparts", "coords"])
    pd.DataFrame(sel.reshape(len(sel), -1), columns=cols).to_csv(out / f"windows_{model}.csv")
    return len(b)


def cmd_collect(rv, name: str) -> None:
    import cv2
    d = bundle_dir(rv, name)
    tasks = pd.read_csv(d / "tasks.tsv", sep="\t", dtype=str)
    from wfield_local import dlc_project
    sp = dlc_project.project_dir(rv).parent / "session_poses"
    for r in tasks.itertuples():
        od = d / "out" / f"{r.animal}_{r.date}"
        done = od / f"{Path(r.video).stem}_done.json"
        if not done.exists():
            print(f"{r.animal} {r.date} {r.video}: NOT DONE (no {done.name})")
            continue
        info = json.loads(done.read_text(encoding="utf-8"))
        v = next(x for x in videos_for(rv, r.animal, r.date) if x.name == r.video)
        n_local = int(cv2.VideoCapture(str(v)).get(cv2.CAP_PROP_FRAME_COUNT))
        npz = od / f"{Path(r.video).stem}_{info['scorer']}.npz"
        ok = info["n_frames"] == n_local and npz.exists()
        print(f"{r.animal} {r.date} {r.video}: {info['n_frames']} frames predicted, video {n_local} "
              f"{'OK' if ok else 'MISMATCH'} ({info['wall_s'] / 3600:.1f} h, batch {info['batch']})")
        if ok:
            z = np.load(npz)
            n = full_to_windows(z["pose"], [str(x) for x in z["parts"]], info["scorer"], r.animal, r.date,
                                sp / f"{r.animal}_{r.date}_full", rv)
            print(f"   -> {sp / (r.animal + '_' + r.date + '_full')} ({n} trials)")


def main(argv=None) -> int:
    from wfield_local.paths import PathResolver
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("bundle")
    b.add_argument("--name", required=True)
    b.add_argument("--user", required=True, help="O2 (HMS) username")
    b.add_argument("sessions", nargs="+", help="animal:date")
    b.add_argument("--refresh", action="store_true", help="existing bundle: rewrite only sbatch / COMMANDS / runner")
    c = sub.add_parser("collect")
    c.add_argument("--name", required=True)
    a = ap.parse_args(argv)
    rv = PathResolver()
    if a.cmd == "bundle":
        cmd_bundle(rv, a.name, a.user, [tuple(s.split(":")) for s in a.sessions], refresh=a.refresh)
    else:
        cmd_collect(rv, a.name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
