"""LIST THE DECK'S QUANTITATIVE CLAIMS SO THEY CAN BE RE-MEASURED, and say which kind each is.

    PYTHONPATH=$(pwd) python scripts/deck_claim_audit.py [docs/DECK_CLAIM_AUDIT.md]

The deck's speaker notes carry several hundred measured numbers. One blanket disclaimer already
sits in the deck -- "EVERY NUMBER QUOTED IN THESE NOTES WAS COMPUTED WITH THE ENGAGED CUT AT 2.0 s
... the numbers written into this prose are pre-change until re-measured" (the cut moved to the
task's real 3.5 s window on 2026-08-21) -- but a disclaimer is not an audit. Nobody can act on
"some of these are stale". This turns it into a list with line numbers.

WHY WHOLE NOTES, NOT SOURCE LINES. The notes are multi-line implicitly-concatenated string
literals; splitting on newlines cuts one claim into fragments and classifies each of them wrongly
(227 "candidate claims" by that method against 177 real notes). `ast` gives the joined constant.

THE CLASSES, in the order they need attention:

  PERF     a measured result whose value the engaged-cut change moves -- decoding, encoding,
           coding-direction projections, correlations. Re-measure.
  ANIMAL   an animal-specific number that is not obviously a performance metric -- trial counts,
           latencies, session-level facts. Mostly stable, but check what generated it.
  OTHER    decimal values that are thresholds or fractions, i.e. parameters rather than results.
  PROSE    no decimal value at all. Cannot go stale by re-measurement, though it can still be
           contradicted by a finding -- which is a different audit.

A SECOND CRITERION, from the 2026-08-24 coding-direction audit: `dom_orth` and `lr` still disagree
by 0.12-0.19 with correlations as low as +0.41 (PS95) even after orthogonalising, so the two methods
are NOT interchangeable. Any claim resting on a FINE ORDERING between adjacent cells needs checking
in both, not only re-measuring in one. Those are flagged ORDERING below.
"""
import ast
import re
import sys
from collections import defaultdict
from pathlib import Path

SRC = Path("wfield_local/locanmf_analysis_deck.py")

ANIMAL = re.compile(r"PS9[2345]")
PERF = re.compile(r"\b(accurac|decod|encod|chance|FEVE|recall|AUC|confusion|coding direction|"
                  r"projection|correlat)", re.IGNORECASE)
ORDERING = re.compile(r"\b(highest|lowest|worst|best|exceeds?|larger than|smaller than|"
                      r"ordering|ranks?|more than|less than)\b", re.IGNORECASE)
NUMVAL = re.compile(r"[-+]?\d*\.\d+")


def notes(path):
    """(lineno, joined text) for every string constant long enough to be a speaker note."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    found = [(n.lineno, " ".join(n.value.split()))
             for n in ast.walk(tree)
             if isinstance(n, ast.Constant) and isinstance(n.value, str) and len(n.value) > 80]
    seen, out = set(), []
    for ln, t in sorted(found):
        if t not in seen:
            seen.add(t)
            out.append((ln, t))
    return out


def classify(t):
    if not NUMVAL.findall(t):
        return "PROSE"
    if PERF.search(t):
        return "PERF"
    if ANIMAL.search(t):
        return "ANIMAL"
    return "OTHER"


buckets = defaultdict(list)
for ln, t in notes(SRC):
    buckets[classify(t)].append((ln, t, len(NUMVAL.findall(t)), bool(ORDERING.search(t))))

HEADER = ("and why the deck's existing blanket staleness disclaimer is not a substitute for "
          "this list.")
out = ["# Deck claim audit", "",
       "Generated by `scripts/deck_claim_audit.py` -- see its docstring for what each class means",
       HEADER, ""]
total_vals = sum(v for b in buckets.values() for _l, _t, v, _o in b)
out.append(f"**{sum(len(v) for v in buckets.values())} speaker notes, "
           f"{total_vals} decimal values.**")
out.append("")
for k in ("PERF", "ANIMAL", "OTHER", "PROSE"):
    b = buckets.get(k, [])
    out.append(f"- `{k}` -- {len(b)} notes, {sum(v for _l, _t, v, _o in b)} decimal values")
for k in ("PERF", "ANIMAL", "OTHER"):
    b = buckets.get(k, [])
    if not b:
        continue
    out += ["", f"## {k} ({len(b)} notes)", ""]
    for ln, t, v, order in sorted(b):
        flag = "  **[ORDERING -- check in `dom_orth` AND `lr`]**" if order else ""
        out.append(f"- [ ] **L{ln}** ({v} values){flag}")
        out.append(f"      {t[:400]}")
        out.append("")

dest = Path(sys.argv[1] if len(sys.argv) > 1 else "docs/DECK_CLAIM_AUDIT.md")
dest.write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"wrote {dest}: {sum(len(v) for v in buckets.values())} notes, {total_vals} values")

